### ISSUE TITLE
bug with command 'stand'

### ISSUE THREAD

**Issue by Kas-O-dam** [Jpgudim/Blackjack-2.0#1]
![bj-bug](https://github.com/Jpgudim/Blackjack-2.0/assets/100534559/290f4b2c-bed6-4c45-8836-0d4494125dd5)

**Comment by Kas-O-dam** [comment]
This was after pull

**Comment by Kas-O-dam** [comment]
I found error, edit that 80th line to solution 
```python
decision = input("What would you like to do? (hit or stand) ")
```
replace var 'decision' to 'turn'

**Comment by Jpgudim** [comment]
Thanks for pointing this out. I will fix it.
