### ISSUE TITLE
Bug with hands

### ISSUE THREAD

**Issue by Kas-O-dam** [Jpgudim/Blackjack-2.0#2]
![Screenshot_20230817_165439](https://github.com/Jpgudim/Blackjack-2.0/assets/100534559/93c55576-4678-450d-a80e-a1c001de3990)
I have 47 points after first game, you should reset user and dealer hand in new game.

**Comment by Kas-O-dam** [comment]
Add this code to line 224, in the 'while' cycle with option 'y'
```Python
dealer_hand.clear()
player_hand.clear()
```

**Comment by Jpgudim** [comment]
Thanks
